# Library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC

In [2]:
datatest=pd.read_csv('Data_Prediction.csv', sep=';')
datatrain=pd.read_csv('DataTrain_Preliminary.csv', sep=';')

In [3]:
datatest

,id,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
0,1,1,tcp,smtp,SF,2397,328,0,0,0,...,179,182,0.68,0.02,0.01,0.01,0.0,0.0,0.0,0.0
1,2,990,udp,other,SF,145,105,0,0,0,...,255,1,0.00,0.64,0.94,0.00,0.0,0.0,0.0,0.0
2,3,0,icmp,ecr_i,SF,1032,0,0,0,0,...,255,23,0.09,0.02,0.09,0.00,0.0,0.0,0.0,0.0
3,4,0,icmp,eco_i,SF,8,0,0,0,0,...,1,85,1.00,0.00,1.00,0.51,0.0,0.0,0.0,0.0
4,5,0,udp,domain_u,SF,44,132,0,0,0,...,250,101,0.40,0.01,0.38,0.00,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12474,12475,0,tcp,http,SF,320,1673,0,0,0,...,127,255,1.00,0.00,0.01,0.06,0.0,0.0,0.0,0.0
12475,12476,21410,tcp,private,RSTR,1,0,0,0,0,...,255,2,0.01,0.69,1.00,0.00,0.0,0.0,1.0,1.0
12476,12477,1,tcp,smtp,SF,743,371,0,0,0,...,6,207,1.00,0.00,0.17,0.01,0.0,0.0,0.0,0.0
12477,12478,0,icmp,eco_i,SF,8,0,0,0,0,...,4,168,1.00,0.00,1.00,0.25,0.0,0.0,0.0,0.0
12478,12479,0,tcp,http,SF,331,14717,0,0,0,...,255,255,1.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0

In [4]:
datatrain

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
0,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.01,0.94,0.95,0,0.95,1,0,0,nmap
1,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
2,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
3,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
4,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112441,0,tcp,http,REJ,0,0,0,0,0,0,...,255,1.00,0.00,0.14,*,0.00,0,*,*,normal
112442,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
112443,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
112444,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
112445,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

# Data Preprocessing

## Data Train

### Missing Value

In [5]:
#Handling Missing Values
datatrain.isna().sum()

duration                          0
protocol_type                   668
service                        1020
flag                            853
src_bytes                         0
dst_bytes                         0
land                              0
wrong_fragment                    0
urgent                            0
hot                               0
num_failed_logins                 0
logged_in                         0
num_compromised                   0
root_shell                        0
su_attempted                      0
num_root                          0
num_file_creations                0
num_shells                        0
num_access_files                  0
num_outbound_cmds                 0
is_host_login                     0
is_guest_login                    0
count                             0
srv_count                         0
serror_rate                       0
srv_serror_rate                   0
rerror_rate                       0
srv_rerror_rate                   0
same_srv_rate                     0
diff_srv_rate                     0
srv_diff_host_rate                0
dst_host_count                    0
dst_host_srv_count                0
dst_host_same_srv_rate          328
dst_host_diff_srv_rate          243
dst_host_same_src_port_rate     438
dst_host_srv_diff_host_rate       0
dst_host_serror_rate            428
dst_host_srv_serror_rate          0
dst_host_rerror_rate              0
dst_host_srv_rerror_rate          0
type_of_attack                    0
dtype: int64

In [6]:
datatrain = datatrain.dropna()
datatrain.reset_index(drop=True, inplace=True)
datatrain.index +=1
datatrain

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
1,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.01,0.94,0.95,0,0.95,1,0,0,nmap
2,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
3,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
4,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
5,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108662,0,tcp,http,REJ,0,0,0,0,0,0,...,255,1.00,0.00,0.14,*,0.00,0,*,*,normal
108663,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
108664,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
108665,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
108666,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

In [7]:
datatrain.isna().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
type_of_attack                 0
dtype: int64

### Duplicate Values

In [8]:
duplicate_rows = datatrain[datatrain.duplicated()]
duplicate_rows

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
2351,0,tcp,other,REJ,0,0,0,0,0,0,...,1,0.00,1.00,0.00,0,0.26,0,*,1,satan
2932,0,tcp,http,REJ,0,0,0,0,0,0,...,255,1.00,0.00,0.50,*,0.00,0,1,*,normal
3284,0,tcp,http,REJ,0,0,0,0,0,0,...,255,1.00,0.00,0.50,*,0.00,0,1,*,normal
4007,0,tcp,other,REJ,0,0,0,0,0,0,...,1,0.00,1.00,0.00,0,0.18,0,*,1,satan
4540,0,icmp,eco_i,SF,8,0,0,0,0,0,...,73,1.00,0.00,1.00,*,0.00,0,0,0,ipsweep
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108530,0,tcp,other,REJ,0,0,0,0,0,0,...,1,0.00,1.00,0.00,0,0.19,0,*,1,satan
108546,0,tcp,other,REJ,0,0,0,0,0,0,...,1,0.00,1.00,0.00,0,0.24,0,*,1,satan
108608,0,tcp,other,REJ,0,0,0,0,0,0,...,1,0.00,1.00,0.00,0,0.10,0,*,1,satan
108614,0,tcp,private,S0,0,0,0,0,0,0,...,23,0.09,0.06,0.00,0,1.00,1,0,0,neptune
108662,0,tcp,http,REJ,0,0,0,0,0,0,...,255,1.00,0.00,0.14,*,0.00,0,*,*,normal

In [9]:
#Drop Duplicates
datatrainclean = datatrain.drop_duplicates()
datatrainclean.reset_index(drop=True, inplace=True)
datatrainclean.index +=1
datatrainclean

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
1,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.01,0.94,0.95,0,0.95,1,0,0,nmap
2,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
3,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
4,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
5,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107268,5,tcp,smtp,SF,1377,328,0,0,0,0,...,117,0.66,0.03,0.01,0,0.00,0,0,0,normal
107269,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
107270,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
107271,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
107272,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

In [10]:
datatrainclean

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
1,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.01,0.94,0.95,0,0.95,1,0,0,nmap
2,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
3,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
4,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
5,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107268,5,tcp,smtp,SF,1377,328,0,0,0,0,...,117,0.66,0.03,0.01,0,0.00,0,0,0,normal
107269,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
107270,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
107271,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
107272,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

## Data Test

### Missing Value

In [11]:
#Handling Missing Values
datatest.isna().sum()

id                             0
duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
dtype: int64

### Duplicate Values

In [12]:
duplicate_rows = datatest[datatest.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [id, duration, protocol_type, service, flag, src_bytes, dst_bytes, land, wrong_fragment, urgent, hot, num_failed_logins, logged_in, num_compromised, root_shell, su_attempted, num_root, num_file_creations, num_shells, num_access_files, num_outbound_cmds, is_host_login, is_guest_login, count, srv_count, serror_rate, srv_serror_rate, rerror_rate, srv_rerror_rate, same_srv_rate, diff_srv_rate, srv_diff_host_rate, dst_host_count, dst_host_srv_count, dst_host_same_srv_rate, dst_host_diff_srv_rate, dst_host_same_src_port_rate, dst_host_srv_diff_host_rate, dst_host_serror_rate, dst_host_srv_serror_rate, dst_host_rerror_rate, dst_host_srv_rerror_rate]
Index: []

[0 rows x 42 columns]

# Feature Encoding

## Data Train

In [13]:
datatrainclean

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
1,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.01,0.94,0.95,0,0.95,1,0,0,nmap
2,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
3,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
4,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
5,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107268,5,tcp,smtp,SF,1377,328,0,0,0,0,...,117,0.66,0.03,0.01,0,0.00,0,0,0,normal
107269,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
107270,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
107271,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
107272,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

In [14]:
datatrainclean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107272 entries, 1 to 107272
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     107272 non-null  object
 1   protocol_type                107272 non-null  object
 2   service                      107272 non-null  object
 3   flag                         107272 non-null  object
 4   src_bytes                    107272 non-null  object
 5   dst_bytes                    107272 non-null  object
 6   land                         107272 non-null  object
 7   wrong_fragment               107272 non-null  object
 8   urgent                       107272 non-null  object
 9   hot                          107272 non-null  object
 10  num_failed_logins            107272 non-null  object
 11  logged_in                    107272 non-null  object
 12  num_compromised              107272 non-null  object
 13  root_shell                   107272 non-null  object
 14  su_attempted                 107272 non-null  object
 15  num_root                     107272 non-null  object
 16  num_file_creations           107272 non-null  object
 17  num_shells                   107272 non-null  object
 18  num_access_files             107272 non-null  object
 19  num_outbound_cmds            107272 non-null  object
 20  is_host_login                107272 non-null  object
 21  is_guest_login               107272 non-null  object
 22  count                        107272 non-null  object
 23  srv_count                    107272 non-null  object
 24  serror_rate                  107272 non-null  object
 25  srv_serror_rate              107272 non-null  object
 26  rerror_rate                  107272 non-null  object
 27  srv_rerror_rate              107272 non-null  object
 28  same_srv_rate                107272 non-null  object
 29  diff_srv_rate                107272 non-null  object
 30  srv_diff_host_rate           107272 non-null  object
 31  dst_host_count               107272 non-null  object
 32  dst_host_srv_count           107272 non-null  object
 33  dst_host_same_srv_rate       107272 non-null  float64
 34  dst_host_diff_srv_rate       107272 non-null  float64
 35  dst_host_same_src_port_rate  107272 non-null  float64
 36  dst_host_srv_diff_host_rate  107272 non-null  object
 37  dst_host_serror_rate         107272 non-null  float64
 38  dst_host_srv_serror_rate     107272 non-null  object
 39  dst_host_rerror_rate         107272 non-null  object
 40  dst_host_srv_rerror_rate     107272 non-null  object
 41  type_of_attack               107272 non-null  object
dtypes: float64(4), object(38)
memory usage: 34.4+ MB

In [15]:
datatrain_object = datatrainclean.select_dtypes(include='object').columns
datatrain_object1 = datatrainclean.drop('type_of_attack', axis=1)

In [16]:
label_encoder = LabelEncoder()

for kolom in datatrain_object1:
    datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])

datatrainclean.head()

C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])
C:\Users\Rahel Cecilia\AppData\Local\Temp\ipykernel_5408\1147163619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datatrainclean[kolom] = label_encoder.fit_transform(datatrainclean[kolom])

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
1,1,1,49,10,1,1,1,1,1,1,...,2,1,94,95,1,95,2,1,1,nmap
2,1,1,49,5,1,1,1,1,1,1,...,202,2,8,0,1,100,2,1,1,neptune
3,1,1,24,9,1877,4902,1,1,1,1,...,145,100,0,1,0,0,1,1,1,normal
4,1,1,24,9,1543,6604,1,1,1,1,...,175,100,0,17,0,0,1,1,1,normal
5,2,1,54,9,112,4517,1,1,1,1,...,63,58,2,0,0,0,1,1,1,normal

In [17]:
datatrainclean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107272 entries, 1 to 107272
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     107272 non-null  int32
 1   protocol_type                107272 non-null  int32
 2   service                      107272 non-null  int32
 3   flag                         107272 non-null  int32
 4   src_bytes                    107272 non-null  int32
 5   dst_bytes                    107272 non-null  int32
 6   land                         107272 non-null  int32
 7   wrong_fragment               107272 non-null  int32
 8   urgent                       107272 non-null  int32
 9   hot                          107272 non-null  int32
 10  num_failed_logins            107272 non-null  int32
 11  logged_in                    107272 non-null  int32
 12  num_compromised              107272 non-null  int32
 13  root_shell                   107272 non-null  int32
 14  su_attempted                 107272 non-null  int32
 15  num_root                     107272 non-null  int32
 16  num_file_creations           107272 non-null  int32
 17  num_shells                   107272 non-null  int32
 18  num_access_files             107272 non-null  int32
 19  num_outbound_cmds            107272 non-null  int32
 20  is_host_login                107272 non-null  int32
 21  is_guest_login               107272 non-null  int32
 22  count                        107272 non-null  int32
 23  srv_count                    107272 non-null  int32
 24  serror_rate                  107272 non-null  int32
 25  srv_serror_rate              107272 non-null  int32
 26  rerror_rate                  107272 non-null  int32
 27  srv_rerror_rate              107272 non-null  int32
 28  same_srv_rate                107272 non-null  int32
 29  diff_srv_rate                107272 non-null  int32
 30  srv_diff_host_rate           107272 non-null  int32
 31  dst_host_count               107272 non-null  int32
 32  dst_host_srv_count           107272 non-null  int32
 33  dst_host_same_srv_rate       107272 non-null  int64
 34  dst_host_diff_srv_rate       107272 non-null  int64
 35  dst_host_same_src_port_rate  107272 non-null  int64
 36  dst_host_srv_diff_host_rate  107272 non-null  int32
 37  dst_host_serror_rate         107272 non-null  int64
 38  dst_host_srv_serror_rate     107272 non-null  int32
 39  dst_host_rerror_rate         107272 non-null  int32
 40  dst_host_srv_rerror_rate     107272 non-null  int32
 41  type_of_attack               107272 non-null  object
dtypes: int32(37), int64(4), object(1)
memory usage: 19.2+ MB

## Data Test

In [18]:
datatest

,id,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
0,1,1,tcp,smtp,SF,2397,328,0,0,0,...,179,182,0.68,0.02,0.01,0.01,0.0,0.0,0.0,0.0
1,2,990,udp,other,SF,145,105,0,0,0,...,255,1,0.00,0.64,0.94,0.00,0.0,0.0,0.0,0.0
2,3,0,icmp,ecr_i,SF,1032,0,0,0,0,...,255,23,0.09,0.02,0.09,0.00,0.0,0.0,0.0,0.0
3,4,0,icmp,eco_i,SF,8,0,0,0,0,...,1,85,1.00,0.00,1.00,0.51,0.0,0.0,0.0,0.0
4,5,0,udp,domain_u,SF,44,132,0,0,0,...,250,101,0.40,0.01,0.38,0.00,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12474,12475,0,tcp,http,SF,320,1673,0,0,0,...,127,255,1.00,0.00,0.01,0.06,0.0,0.0,0.0,0.0
12475,12476,21410,tcp,private,RSTR,1,0,0,0,0,...,255,2,0.01,0.69,1.00,0.00,0.0,0.0,1.0,1.0
12476,12477,1,tcp,smtp,SF,743,371,0,0,0,...,6,207,1.00,0.00,0.17,0.01,0.0,0.0,0.0,0.0
12477,12478,0,icmp,eco_i,SF,8,0,0,0,0,...,4,168,1.00,0.00,1.00,0.25,0.0,0.0,0.0,0.0
12478,12479,0,tcp,http,SF,331,14717,0,0,0,...,255,255,1.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0

In [19]:
datatest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12479 entries, 0 to 12478
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           12479 non-null  int64
 1   duration                     12479 non-null  int64
 2   protocol_type                12479 non-null  object
 3   service                      12479 non-null  object
 4   flag                         12479 non-null  object
 5   src_bytes                    12479 non-null  int64
 6   dst_bytes                    12479 non-null  int64
 7   land                         12479 non-null  int64
 8   wrong_fragment               12479 non-null  int64
 9   urgent                       12479 non-null  int64
 10  hot                          12479 non-null  int64
 11  num_failed_logins            12479 non-null  int64
 12  logged_in                    12479 non-null  int64
 13  num_compromised              12479 non-null  int64
 14  root_shell                   12479 non-null  int64
 15  su_attempted                 12479 non-null  int64
 16  num_root                     12479 non-null  int64
 17  num_file_creations           12479 non-null  int64
 18  num_shells                   12479 non-null  int64
 19  num_access_files             12479 non-null  int64
 20  num_outbound_cmds            12479 non-null  int64
 21  is_host_login                12479 non-null  int64
 22  is_guest_login               12479 non-null  int64
 23  count                        12479 non-null  int64
 24  srv_count                    12479 non-null  int64
 25  serror_rate                  12479 non-null  float64
 26  srv_serror_rate              12479 non-null  float64
 27  rerror_rate                  12479 non-null  float64
 28  srv_rerror_rate              12479 non-null  float64
 29  same_srv_rate                12479 non-null  float64
 30  diff_srv_rate                12479 non-null  float64
 31  srv_diff_host_rate           12479 non-null  float64
 32  dst_host_count               12479 non-null  int64
 33  dst_host_srv_count           12479 non-null  int64
 34  dst_host_same_srv_rate       12479 non-null  float64
 35  dst_host_diff_srv_rate       12479 non-null  float64
 36  dst_host_same_src_port_rate  12479 non-null  float64
 37  dst_host_srv_diff_host_rate  12479 non-null  float64
 38  dst_host_serror_rate         12479 non-null  float64
 39  dst_host_srv_serror_rate     12479 non-null  float64
 40  dst_host_rerror_rate         12479 non-null  float64
 41  dst_host_srv_rerror_rate     12479 non-null  float64
dtypes: float64(15), int64(24), object(3)
memory usage: 4.0+ MB

In [20]:
datatest_object = datatest.select_dtypes(include='object').columns

In [21]:
label_encoder = LabelEncoder()

for kolom_test in datatest_object:
    datatest[kolom_test] = label_encoder.fit_transform(datatest[kolom_test])

datatest.head()

,id,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
0,1,1,1,50,9,2397,328,0,0,0,...,179,182,0.68,0.02,0.01,0.01,0.0,0.0,0.0,0.0
1,2,990,2,41,9,145,105,0,0,0,...,255,1,0.00,0.64,0.94,0.00,0.0,0.0,0.0,0.0
2,3,0,0,14,9,1032,0,0,0,0,...,255,23,0.09,0.02,0.09,0.00,0.0,0.0,0.0,0.0
3,4,0,0,13,9,8,0,0,0,0,...,1,85,1.00,0.00,1.00,0.51,0.0,0.0,0.0,0.0
4,5,0,2,11,9,44,132,0,0,0,...,250,101,0.40,0.01,0.38,0.00,0.0,0.0,0.0,0.0

In [22]:
datatest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12479 entries, 0 to 12478
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           12479 non-null  int64
 1   duration                     12479 non-null  int64
 2   protocol_type                12479 non-null  int32
 3   service                      12479 non-null  int32
 4   flag                         12479 non-null  int32
 5   src_bytes                    12479 non-null  int64
 6   dst_bytes                    12479 non-null  int64
 7   land                         12479 non-null  int64
 8   wrong_fragment               12479 non-null  int64
 9   urgent                       12479 non-null  int64
 10  hot                          12479 non-null  int64
 11  num_failed_logins            12479 non-null  int64
 12  logged_in                    12479 non-null  int64
 13  num_compromised              12479 non-null  int64
 14  root_shell                   12479 non-null  int64
 15  su_attempted                 12479 non-null  int64
 16  num_root                     12479 non-null  int64
 17  num_file_creations           12479 non-null  int64
 18  num_shells                   12479 non-null  int64
 19  num_access_files             12479 non-null  int64
 20  num_outbound_cmds            12479 non-null  int64
 21  is_host_login                12479 non-null  int64
 22  is_guest_login               12479 non-null  int64
 23  count                        12479 non-null  int64
 24  srv_count                    12479 non-null  int64
 25  serror_rate                  12479 non-null  float64
 26  srv_serror_rate              12479 non-null  float64
 27  rerror_rate                  12479 non-null  float64
 28  srv_rerror_rate              12479 non-null  float64
 29  same_srv_rate                12479 non-null  float64
 30  diff_srv_rate                12479 non-null  float64
 31  srv_diff_host_rate           12479 non-null  float64
 32  dst_host_count               12479 non-null  int64
 33  dst_host_srv_count           12479 non-null  int64
 34  dst_host_same_srv_rate       12479 non-null  float64
 35  dst_host_diff_srv_rate       12479 non-null  float64
 36  dst_host_same_src_port_rate  12479 non-null  float64
 37  dst_host_srv_diff_host_rate  12479 non-null  float64
 38  dst_host_serror_rate         12479 non-null  float64
 39  dst_host_srv_serror_rate     12479 non-null  float64
 40  dst_host_rerror_rate         12479 non-null  float64
 41  dst_host_srv_rerror_rate     12479 non-null  float64
dtypes: float64(15), int32(3), int64(24)
memory usage: 3.9 MB

# Splitting Data

In [23]:
X = datatrainclean.drop('type_of_attack', axis=1)
Y =  datatrainclean['type_of_attack']
datatest = datatest.drop('id',axis=1)

X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=40)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((85817, 41), (21455, 41), (85817,), (21455,))

# Model Development

## SVM

In [35]:
svm=SVC()
svm.fit(X_train,y_train)

SVC()

In [36]:
y_pred_svm = svm.predict(X_test)
y_pred_svm

array(['neptune', 'neptune', 'neptune', ..., 'normal', 'normal', 'normal'],
      dtype=object)

## Model Predict

In [37]:
result = svm.predict(datatest)

In [38]:
data = datatest.copy()
data["type_of_attack"] = result
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
0,1,1,50,9,2397,328,0,0,0,0,...,182,0.68,0.02,0.01,0.01,0.0,0.0,0.0,0.0,normal
1,990,2,41,9,145,105,0,0,0,0,...,1,0.00,0.64,0.94,0.00,0.0,0.0,0.0,0.0,portsweep
2,0,0,14,9,1032,0,0,0,0,0,...,23,0.09,0.02,0.09,0.00,0.0,0.0,0.0,0.0,normal
3,0,0,13,9,8,0,0,0,0,0,...,85,1.00,0.00,1.00,0.51,0.0,0.0,0.0,0.0,neptune
4,0,2,11,9,44,132,0,0,0,0,...,101,0.40,0.01,0.38,0.00,0.0,0.0,0.0,0.0,neptune

## Accuracy

In [39]:
accuracy_svm = svm.score(X_test,y_test)
print("Accuracy:", accuracy_svm)

Accuracy: 0.9320438126310884